### ISSUE TITLE
Error creating app

### ISSUE THREAD

**Issue by andypiper** [hairymnstr/Flopagon#2]
Firmware 1.6.0

App fails to start, error at the console is

`Error creating app: function takes 3 positional arguments but 2 were given`

**Comment by andypiper** [comment]
Also, I think this is missing `__init__.py` which should be as simple as:

```python
from .app import FlopagonApp
```

**Comment by hairymnstr** [comment]
Might be because you've copied the `app.mpy` file instead (or as well as) the `app.py`.

`app.mpy` was a compiled (and therefore smaller) version of the app that fits on the EEPROM (only on the patched eerpom_stuff branch of main firmware).  This only works if it's launched from a hexpansion where the hexpansion port config is passed to the app as an extra argument.

`app.py` has some extra code in that defaults the location to slot 2 if you're running the code from the badge instead of a hexpansion EEPROM so shouldn't throw this error.

The app loading is a bit esoteric but at least on 1.5.0 `app.py` on its own in a folder /apps/flopagon should work.

**Comment by andypiper** [comment]
Yes - you're right, I wasn't paying attention and just did a `cp *`, without the `app.mpy` we are all set, Flopagon formats and mounts ✅ thank you!
